In [1]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("/content/Bangalore_Ride_Forensics_Duplicates.csv")

,ID,Time,Day,Hour,Pickup,Dropoff,Dist_KM,Est_Min,Traffic,Weather,...,Device,Battery,AppOpens,Tenure_Mo,Acc_Rate,BaseFare,Surge,QuoteFare,CompDiff,Status
0,e7d202a2,03-06-2026 08:27,2.0,8.0,Marathahalli,Indiranagar,8.9,54.0,Heavy,Clear,...,Mid-Range,79.0,2.0,42.0,0.68,NaN,1.13,151.0,36.0,Cancelled_By_Driver
1,21cdeab4,NaN,4.0,6.0,Electronic City,Peenya,6.6,38.0,Free-Flow,Heavy Downpour,...,Budget,22.0,NaN,38.0,0.66,99.0,1.40,139.0,12.0,Ride_Accepted
2,705ab73c,18-05-2026 19:33,0.0,19.0,Peenya,Koramangala,9.4,40.0,Moderate,Light Rain,...,Premium,96.0,1.0,34.0,0.81,141.0,2.33,NaN,-24.0,Ride_Accepted
3,bcc9cf43,19-05-2026 15:43,1.0,15.0,HSR Layout,Peenya,13.8,61.0,Moderate,Clear,...,Budget,55.0,3.0,47.0,0.78,207.0,0.90,186.0,14.0,User_Abandoned_App
4,ea0c8226,20-06-2026 00:25,5.0,0.0,Marathahalli,Koramangala,27.4,80.0,Light,Clear,...,Mid-Range,80.0,1.0,3.0,0.89,411.0,1.10,453.0,-13.0,User_Abandoned_App

In [2]:
dup_mask = df.duplicated(keep= False)
df.duplicated().sum()

NameError: name 'df' is not defined

In [16]:
df[dup_mask].sort_values("ID")
dup_ids = df[df["ID"].duplicated(keep=False)].sort_values("ID")
dup_ids

,ID,Time,Day,Hour,Pickup,Dropoff,Dist_KM,Est_Min,Traffic,Weather,...,Device,Battery,AppOpens,Tenure_Mo,Acc_Rate,BaseFare,Surge,QuoteFare,CompDiff,Status
31624,002163ec,30-04-2026 07:15,3.0,7.0,Bellandur,Koramangala,7.1,47.0,Moderate,Heavy Downpour,...,Mid-Range,NaN,8.0,9.0,0.90,106.5,1.70,181.0,15.0,Ride_Accepted
31625,002163ec,30-04-2026 07:15,3.0,7.0,Bellandur,Koramangala,7.1,47.0,Moderate,Heavy Downpour,...,Mid-Range,NaN,8.0,9.0,0.90,106.5,1.70,181.0,15.0,Ride_Accepted
31623,002163ec,30-04-2026 07:15,3.0,7.0,Bellandur,Koramangala,7.1,47.0,Moderate,Heavy Downpour,...,Mid-Range,NaN,8.0,9.0,0.90,106.5,1.70,181.0,15.0,Ride_Accepted
7345,006a2c5d,26-05-2026 05:45,1.0,5.0,Malleshwaram,Whitefield,16.0,46.0,Free-Flow,Clear,...,Budget,58.0,1.0,1.0,0.90,240.0,NaN,253.0,-4.0,Ride_Accepted
7346,006a2c5d,26-05-2026 05:45,1.0,5.0,Malleshwaram,Whitefield,16.0,46.0,Free-Flow,Clear,...,Budget,58.0,1.0,1.0,0.90,240.0,NaN,253.0,-4.0,Ride_Accepted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35587,NaN,13-06-2026 20:01,5.0,20.0,Electronic City,Indiranagar,14.9,104.0,Gridlock,Clear,...,Mid-Range,25.0,3.0,25.0,0.47,223.5,1.39,310.0,-4.0,Ride_Accepted
35606,NaN,30-05-2026 17:08,5.0,17.0,Electronic City,Hebbal,15.3,NaN,Gridlock,Clear,...,Mid-Range,19.0,2.0,16.0,0.52,229.5,1.40,321.0,-27.0,Ride_Accepted
35613,NaN,29-04-2026 04:59,2.0,4.0,Electronic City,Peenya,6.2,16.0,Light,Clear,...,Premium,81.0,NaN,46.0,0.90,93.0,1.29,120.0,NaN,Ride_Accepted
35622,NaN,13-03-2026 08:32,4.0,8.0,HSR Layout,WHITEFIELD,25.7,151.0,Heavy,Clear,...,Mid-Range,92.0,1.0,2.0,NaN,385.5,1.28,493.0,-20.0,Ride_Accepted
35675,NaN,16-06-2026 16:16,1.0,16.0,NaN,Marathahalli,11.5,74.0,Free-Flow,Thunderstorm,...,Premium,16.0,1.0,19.0,0.90,172.5,2.10,363.0,34.0,Ride_Accepted

In [ ]:
for ride_id, group in dup_ids.groupby('ID'):
    print(f"\n ride id is: {ride_id}")
    display(group)

In [ ]:
df1 = df.drop_duplicates()
df_no_dup = df1.copy()
df_no_dup = df.drop_duplicates().copy()

In [ ]:
print('Before:',len(df))

In [ ]:
print("After:", len((df_no_dup)))

In [ ]:
print('Removed Records:', len(df)-len(df_no_dup) )